import type { Metadata } from 'next'
import './globals.scss'
import ReactQuery from '@/components/Store/ReactQuery'


export const metadata: Metadata = {
  title: 'فروشگاه اینترنتی دیجی کالا',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReactQuery>
          {children}
        </ReactQuery>
      </body>
    </html>
  )
}
